"""Build ep1-2min.json (+ captions-2min.json) from the original full timeline (../orig/ep1-full.json).
Keeps the scenes that start before END (a01 ... b03-image-belongs), points the A/B art at ../art-v2/A|B/
(same file names), the title brandmark at the original ../orig/art/00-brandmark.svg, filters the captions
to the window and uses the new drawing hand.   usage: python3 make_preview.py"""
import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
END = 127.65
HAND = json.load(open(os.path.join(HERE, '..', 'engine', 'hand', 'hand.json')))

tl = json.load(open(os.path.join(HERE, '..', 'orig', 'ep1-full.json')))
caps = json.load(open(os.path.join(HERE, '..', 'orig', 'full', 'captions-full.json')))

def art(p):
    if p == 'art/00-brandmark.svg':
        return '../orig/art/00-brandmark.svg'
    for batch in ('A', 'B'):
        if p.startswith(f'art-full/{batch}/'):
            return f'../art-v2/{batch}/' + p.split('/')[-1]
    raise ValueError('unexpected art path: ' + p)

# v2 timing tweaks (seconds after the scene's t0), so the denser v2 art fits its windows:
# {scene id: {"parts": {part index: at}, "text": {text index: t}}}
OVERRIDES = {
    'a06-trap': {'parts': {1: 3.15, 2: 5.75}, 'text': {1: 5.0}},   # part b, part c, "NO"
}

scenes = []
for sc in tl['scenes']:
    if sc['t0'] >= END:
        continue
    sc = dict(sc)
    if 'svg' in sc:
        sc['svg'] = art(sc['svg'])
    if 'parts' in sc:
        sc['parts'] = [dict(p, svg=art(p['svg'])) for p in sc['parts']]
    ov = OVERRIDES.get(sc['id'], {})
    for i, at in ov.get('parts', {}).items():
        sc['parts'][i] = dict(sc['parts'][i], at=at)
    for i, t in ov.get('text', {}).items():
        sc['text'] = [dict(x) for x in sc['text']]
        sc['text'][i]['t'] = t
    scenes.append(sc)

cap = [dict(c, t1=min(c['t1'], END)) for c in caps if c['t0'] < END]
json.dump(cap, open(os.path.join(HERE, 'captions-2min.json'), 'w'), indent=1, ensure_ascii=False)

out = dict(tl)
out['_comment'] = ('Episode 1, first 2 minutes with the v2 art (generated by make_preview.py from ../orig/ep1-full.json). '
                   'Audio: ../audio/ep1.mp3 if present, else the video is silent.')
out['audio'] = '../audio/ep1.mp3'
out['start'], out['end'] = 0, END
out['hand'] = {k: HAND[k] for k in ('image', 'tip', 'scale', 'angle') if k in HAND}
out['hand']['image'] = '../engine/hand/' + os.path.basename(HAND['image'])
out['scenes'] = scenes
out['captions'] = ['captions-2min.json']
keys = ['_comment', 'width', 'height', 'fps', 'audio', 'start', 'end', 'board', 'ink', 'hand', 'scenes', 'captions', 'safeBottom', 'options']
out = {k: out[k] for k in keys if k in out}
json.dump(out, open(os.path.join(HERE, 'ep1-2min.json'), 'w'), indent=1, ensure_ascii=False)
print(f"ep1-2min.json: {len(scenes)} scenes ({scenes[0]['id']} ... {scenes[-1]['id']}), end {END}; "
      f"captions-2min.json: {len(cap)} captions (last ends {cap[-1]['t1']})")
for sc in scenes:
    files = [sc['svg']] if 'svg' in sc else []
    files += [p['svg'] for p in sc.get('parts', [])]
    print(f"  {sc['id']:22s} t0 {sc['t0']:7.2f}  " + ', '.join(files))
